ansible_user: root
ansible_private_key_file: ~/.ssh/id_rsa
ansible_connection: ssh
certificate_authority_urls:
  - https://password.corp.redhat.com/legacy.crt
  - https://password.corp.redhat.com/RH-IT-Root-CA.crt
  - https://engineering.redhat.com/Eng-CA.crt
rhel_base: "http://download.eng.bos.redhat.com/pub/released/RHEL-7/7.4/Server"
